/***************************************************************************//**
 * @file panic.c
 *
 * @see panic.h
 *
 * @author Alexy Torres Aurora Dugo
 *
 * @date 16/12/2017
 *
 * @version 1.0
 *
 * @brief Panic feature of the kernel.
 *
 * @details Kernel panic functions. Displays the CPU registers, the faulty
 * instruction, the interrupt ID and cause.
 *
 * @copyright Alexy Torres Aurora Dugo
 ******************************************************************************/

#include <Interrupt/interrupts.h> /* cpu_state_t, stack_state_t,
                                   * PANIC_INT_LINE */
#include <IO/kernel_output.h>     /* kernel_printf */
#include <Lib/stdint.h>           /* Generic int types */
#include <Cpu/cpu.h>              /* cpu_clear_interrupt */

/* UTK configuration file */
#include <config.h>

/* Header file */
#include <Cpu/panic.h>

/*******************************************************************************
 * GLOBAL VARIABLES
 ******************************************************************************/

/** @brief Stores the current kernel panic error code. */
static uint32_t panic_code = 0;

/*******************************************************************************
 * FUNCTIONS
 ******************************************************************************/

void panic(cpu_state_t* cpu_state, uint32_t int_id, stack_state_t* stack_state)
{
    (void)cpu_state;
    (void)int_id;
    (void)stack_state;
    
    cpu_clear_interrupt();

    /* Test mode probing */
    if(panic_code == 666)
    {
        kernel_printf("\n[TESTMODE] PANIC\n");
    }

    kernel_printf("\n");

    kernel_printf("#=============================    KERNEL PANIC    =========="
                    "==================#\n");

    /* We will never return from interrupt */
    while(1)
    {
        cpu_clear_interrupt();
        cpu_hlt();
    }
}

void kernel_panic(const uint32_t error_code)
{
    /* Save the error code to memory */
    panic_code = error_code;

    /* Raise INT */
    __asm__ __volatile__("swi %0" :: "i" (PANIC_INT_LINE));
}

/*
#=============================    KERNEL PANIC    ============================#
|                                                                             |
| Reason: Panic generated by the kernel           INT ID: 0x2a                |
| Instruction [EIP]: 0x00207b1b                   Error code: 0x00000004      |
|                                                                             |
|================================= CPU STATE =================================|
|                                                                             |
| EAX: 0x00000004  |  EBX: 0x000002ca  |  ECX: 0x000000c8  |  EDX: 0x00000000 |
| ESI: 0x00000000  |  EDI: 0x88888889  |  EBP: 0x003098b8  |  ESP: 0x00309838 |
| CR0: 0x00000000  |  CR2: 0x00000000  |  CR3: 0x00000000  |  CR4: 0x00202f60 |
| EFLAGS: 0x00000216  |                                                       |
|                                                                             |
|============================= SEGMENT REGISTERS =============================|
|                                                                             |
| CS: 0x0008  |  DS: 0x0010  |  SS: 0x0010                                    |
| ES: 0x0010  |  FS: 0x0010  |  GS: 0x0010                                    |
|                                                                             |
|============================== ADDITIONAL INFO ==============================|
|                                                                             |
| Core ID: 0x00000000                                                         |
| Thread:  000000003                                                          |
| Inst:    c3 66 90 66 (Address: 0x00207b1b)                                  |
|                                                                             |
|                         LET'S HOPE IT WON'T EXPLODE                         |
#=============================================================================#
*/